In [1]:
import pandas as pd
import logging
import os

In [2]:
df = pd.read_csv('C:\IDE\data\Block_3\kaggleV2-May-2016.csv')
display(df)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [3]:
import os.path

# функция для создания лог-файла и записи в него информации
def get_logger(path, file):
    """[Создает лог файл для логирования в него]

    Args:
        path (string): - путь к директории
        file (string): - имя файла
       
    Rerurns:
       [obj] - [логер]    
    """
    
    # проверяем, существет ли файл
    log_file = os.path.join(path, file)
    
    # если файла нет, создаем его
    if not os.path.isfile(log_file):
        open(log_file, "w+").close()
    
    # поменяем формат логирования
    file_logging_format = "%(levelname)s: %(asctime)s: %(message)s"
    
    # конфигурируем лог-файл
    logging.basicConfig(level=logging.INFO, format=file_logging_format)
    logger = logging.getLogger()
    
    # создадим хэндлер для записи лога в файл
    handler = logging.FileHandler(log_file)
    
    # установим уровень логирования
    handler.setLevel(logging.INFO)
    
    # создадим формат логирования, используя file_logging_format
    formatter = logging.Formatter(file_logging_format)
    handler.setFormatter(formatter)
    
    # добавим хэндлер лог-файлу
    logger.addHandler(handler)
    return logger

In [5]:
# создаем лог-файл
logger = get_logger(path="C:\IDE\logs", file="data.logs")
logger.info("Data")
logger.info("Data shape {}".format(df.shape))
logger.info("Percentage of women: {}".format(df[df['No-show'] == 'Yes']['Gender'].value_counts(True)[0]))
logger.info("Percentage of men: {}".format(df[df['No-show'] == 'Yes']['Gender'].value_counts(True)[1]))

INFO: 2025-01-19 15:43:04,064: Data
INFO: 2025-01-19 15:43:04,065: Data shape (110527, 14)
C:\Users\HYPERPC\AppData\Local\Temp\ipykernel_1824\1330991220.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  logger.info("Percentage of women: {}".format(df[df['No-show'] == 'Yes']['Gender'].value_counts(True)[0]))
INFO: 2025-01-19 15:43:04,076: Percentage of women: 0.653882342398853
C:\Users\HYPERPC\AppData\Local\Temp\ipykernel_1824\1330991220.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  logger.info("Percentage of men: {}".format(df[df['No-show'] == 'Yes']['Gender'].value_counts(True)[1]))
INFO: 2025-01-19 15:43:04,084: Percentage of men: 0.346117657601147

In [6]:
if df.shape != (110526, 14):
    logger.error('Data shape is incorrect!')

ERROR: 2025-01-19 15:47:06,870: Data shape is incorrect!